// Generated by CoffeeScript 1.10.0

/* (C) 2015 Narazaka : Licensed under The MIT License - http://narazaka.net/license/MIT?2015 */

(function() {
  var wheel_event_name;

  wheel_event_name = 'onwheel' in document ? 'wheel' : 'onmousewheel' in document ? 'mousewheel' : 'DOMMouseScroll';

  this.wheelevent = function(dom, onWheel) {
    var _onWheel, error;
    _onWheel = function(event) {
      var delta;
      if (event == null) {
        event = window.event;
      }
      delta = event.deltaY != null ? event.deltaY : event.wheelDelta ? -event.wheelDelta : event.detail;
      if (delta !== 0) {
        return onWheel(event, delta);
      }
    };
    try {
      return dom.addEventListener(wheel_event_name, _onWheel, false);
    } catch (error) {
      return dom.attachEvent('onmousewheel', _onWheel);
    }
  };

}).call(this);
